/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FeedRouteImport } from './routes/feed'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as BecomeCreatorRouteImport } from './routes/become-creator'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsSecurityRouteImport } from './routes/settings.security'
import { Route as SettingsProfileRouteImport } from './routes/settings.profile'
import { Route as RCodeRouteImport } from './routes/r.$code'
import { Route as ProfileUsernameRouteImport } from './routes/profile.$username'
import { Route as CreatorWalletRouteImport } from './routes/creator.wallet'
import { Route as CreatorSubscriptionPlansRouteImport } from './routes/creator.subscription-plans'
import { Route as CreatorPostsRouteImport } from './routes/creator.posts'
import { Route as CreatorMailingRouteImport } from './routes/creator.mailing'
import { Route as CreatorDmcaRouteImport } from './routes/creator.dmca'
import { Route as CreatorCouponsRouteImport } from './routes/creator.coupons'
import { Route as CreatorAnalyticsRouteImport } from './routes/creator.analytics'
import { Route as CreatorAffiliateRouteImport } from './routes/creator.affiliate'
import { Route as CCodeRouteImport } from './routes/c.$code'
import { Route as AdminModerationRouteImport } from './routes/admin.moderation'
import { Route as AdminKycRouteImport } from './routes/admin.kyc'
import { Route as AdminDmcaRouteImport } from './routes/admin.dmca'
import { Route as ApiPublicHooksProcessMailingQueueRouteImport } from './routes/api.public.hooks.process-mailing-queue'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedRoute = FeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const BecomeCreatorRoute = BecomeCreatorRouteImport.update({
  id: '/become-creator',
  path: '/become-creator',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsSecurityRoute = SettingsSecurityRouteImport.update({
  id: '/settings/security',
  path: '/settings/security',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsProfileRoute = SettingsProfileRouteImport.update({
  id: '/settings/profile',
  path: '/settings/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const RCodeRoute = RCodeRouteImport.update({
  id: '/r/$code',
  path: '/r/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileUsernameRoute = ProfileUsernameRouteImport.update({
  id: '/profile/$username',
  path: '/profile/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorWalletRoute = CreatorWalletRouteImport.update({
  id: '/creator/wallet',
  path: '/creator/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorSubscriptionPlansRoute =
  CreatorSubscriptionPlansRouteImport.update({
    id: '/creator/subscription-plans',
    path: '/creator/subscription-plans',
    getParentRoute: () => rootRouteImport,
  } as any)
const CreatorPostsRoute = CreatorPostsRouteImport.update({
  id: '/creator/posts',
  path: '/creator/posts',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorMailingRoute = CreatorMailingRouteImport.update({
  id: '/creator/mailing',
  path: '/creator/mailing',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorDmcaRoute = CreatorDmcaRouteImport.update({
  id: '/creator/dmca',
  path: '/creator/dmca',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorCouponsRoute = CreatorCouponsRouteImport.update({
  id: '/creator/coupons',
  path: '/creator/coupons',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorAnalyticsRoute = CreatorAnalyticsRouteImport.update({
  id: '/creator/analytics',
  path: '/creator/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorAffiliateRoute = CreatorAffiliateRouteImport.update({
  id: '/creator/affiliate',
  path: '/creator/affiliate',
  getParentRoute: () => rootRouteImport,
} as any)
const CCodeRoute = CCodeRouteImport.update({
  id: '/c/$code',
  path: '/c/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminModerationRoute = AdminModerationRouteImport.update({
  id: '/admin/moderation',
  path: '/admin/moderation',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminKycRoute = AdminKycRouteImport.update({
  id: '/admin/kyc',
  path: '/admin/kyc',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDmcaRoute = AdminDmcaRouteImport.update({
  id: '/admin/dmca',
  path: '/admin/dmca',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksProcessMailingQueueRoute =
  ApiPublicHooksProcessMailingQueueRouteImport.update({
    id: '/api/public/hooks/process-mailing-queue',
    path: '/api/public/hooks/process-mailing-queue',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/become-creator': typeof BecomeCreatorRoute
  '/chat': typeof ChatRoute
  '/explore': typeof ExploreRoute
  '/feed': typeof FeedRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/signup': typeof SignupRoute
  '/admin/dmca': typeof AdminDmcaRoute
  '/admin/kyc': typeof AdminKycRoute
  '/admin/moderation': typeof AdminModerationRoute
  '/c/$code': typeof CCodeRoute
  '/creator/affiliate': typeof CreatorAffiliateRoute
  '/creator/analytics': typeof CreatorAnalyticsRoute
  '/creator/coupons': typeof CreatorCouponsRoute
  '/creator/dmca': typeof CreatorDmcaRoute
  '/creator/mailing': typeof CreatorMailingRoute
  '/creator/posts': typeof CreatorPostsRoute
  '/creator/subscription-plans': typeof CreatorSubscriptionPlansRoute
  '/creator/wallet': typeof CreatorWalletRoute
  '/profile/$username': typeof ProfileUsernameRoute
  '/r/$code': typeof RCodeRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/settings/security': typeof SettingsSecurityRoute
  '/api/public/hooks/process-mailing-queue': typeof ApiPublicHooksProcessMailingQueueRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/become-creator': typeof BecomeCreatorRoute
  '/chat': typeof ChatRoute
  '/explore': typeof ExploreRoute
  '/feed': typeof FeedRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/signup': typeof SignupRoute
  '/admin/dmca': typeof AdminDmcaRoute
  '/admin/kyc': typeof AdminKycRoute
  '/admin/moderation': typeof AdminModerationRoute
  '/c/$code': typeof CCodeRoute
  '/creator/affiliate': typeof CreatorAffiliateRoute
  '/creator/analytics': typeof CreatorAnalyticsRoute
  '/creator/coupons': typeof CreatorCouponsRoute
  '/creator/dmca': typeof CreatorDmcaRoute
  '/creator/mailing': typeof CreatorMailingRoute
  '/creator/posts': typeof CreatorPostsRoute
  '/creator/subscription-plans': typeof CreatorSubscriptionPlansRoute
  '/creator/wallet': typeof CreatorWalletRoute
  '/profile/$username': typeof ProfileUsernameRoute
  '/r/$code': typeof RCodeRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/settings/security': typeof SettingsSecurityRoute
  '/api/public/hooks/process-mailing-queue': typeof ApiPublicHooksProcessMailingQueueRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/become-creator': typeof BecomeCreatorRoute
  '/chat': typeof ChatRoute
  '/explore': typeof ExploreRoute
  '/feed': typeof FeedRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/signup': typeof SignupRoute
  '/admin/dmca': typeof AdminDmcaRoute
  '/admin/kyc': typeof AdminKycRoute
  '/admin/moderation': typeof AdminModerationRoute
  '/c/$code': typeof CCodeRoute
  '/creator/affiliate': typeof CreatorAffiliateRoute
  '/creator/analytics': typeof CreatorAnalyticsRoute
  '/creator/coupons': typeof CreatorCouponsRoute
  '/creator/dmca': typeof CreatorDmcaRoute
  '/creator/mailing': typeof CreatorMailingRoute
  '/creator/posts': typeof CreatorPostsRoute
  '/creator/subscription-plans': typeof CreatorSubscriptionPlansRoute
  '/creator/wallet': typeof CreatorWalletRoute
  '/profile/$username': typeof ProfileUsernameRoute
  '/r/$code': typeof RCodeRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/settings/security': typeof SettingsSecurityRoute
  '/api/public/hooks/process-mailing-queue': typeof ApiPublicHooksProcessMailingQueueRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/become-creator'
    | '/chat'
    | '/explore'
    | '/feed'
    | '/login'
    | '/notifications'
    | '/reset-password'
    | '/search'
    | '/signup'
    | '/admin/dmca'
    | '/admin/kyc'
    | '/admin/moderation'
    | '/c/$code'
    | '/creator/affiliate'
    | '/creator/analytics'
    | '/creator/coupons'
    | '/creator/dmca'
    | '/creator/mailing'
    | '/creator/posts'
    | '/creator/subscription-plans'
    | '/creator/wallet'
    | '/profile/$username'
    | '/r/$code'
    | '/settings/profile'
    | '/settings/security'
    | '/api/public/hooks/process-mailing-queue'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/become-creator'
    | '/chat'
    | '/explore'
    | '/feed'
    | '/login'
    | '/notifications'
    | '/reset-password'
    | '/search'
    | '/signup'
    | '/admin/dmca'
    | '/admin/kyc'
    | '/admin/moderation'
    | '/c/$code'
    | '/creator/affiliate'
    | '/creator/analytics'
    | '/creator/coupons'
    | '/creator/dmca'
    | '/creator/mailing'
    | '/creator/posts'
    | '/creator/subscription-plans'
    | '/creator/wallet'
    | '/profile/$username'
    | '/r/$code'
    | '/settings/profile'
    | '/settings/security'
    | '/api/public/hooks/process-mailing-queue'
  id:
    | '__root__'
    | '/'
    | '/become-creator'
    | '/chat'
    | '/explore'
    | '/feed'
    | '/login'
    | '/notifications'
    | '/reset-password'
    | '/search'
    | '/signup'
    | '/admin/dmca'
    | '/admin/kyc'
    | '/admin/moderation'
    | '/c/$code'
    | '/creator/affiliate'
    | '/creator/analytics'
    | '/creator/coupons'
    | '/creator/dmca'
    | '/creator/mailing'
    | '/creator/posts'
    | '/creator/subscription-plans'
    | '/creator/wallet'
    | '/profile/$username'
    | '/r/$code'
    | '/settings/profile'
    | '/settings/security'
    | '/api/public/hooks/process-mailing-queue'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BecomeCreatorRoute: typeof BecomeCreatorRoute
  ChatRoute: typeof ChatRoute
  ExploreRoute: typeof ExploreRoute
  FeedRoute: typeof FeedRoute
  LoginRoute: typeof LoginRoute
  NotificationsRoute: typeof NotificationsRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SearchRoute: typeof SearchRoute
  SignupRoute: typeof SignupRoute
  AdminDmcaRoute: typeof AdminDmcaRoute
  AdminKycRoute: typeof AdminKycRoute
  AdminModerationRoute: typeof AdminModerationRoute
  CCodeRoute: typeof CCodeRoute
  CreatorAffiliateRoute: typeof CreatorAffiliateRoute
  CreatorAnalyticsRoute: typeof CreatorAnalyticsRoute
  CreatorCouponsRoute: typeof CreatorCouponsRoute
  CreatorDmcaRoute: typeof CreatorDmcaRoute
  CreatorMailingRoute: typeof CreatorMailingRoute
  CreatorPostsRoute: typeof CreatorPostsRoute
  CreatorSubscriptionPlansRoute: typeof CreatorSubscriptionPlansRoute
  CreatorWalletRoute: typeof CreatorWalletRoute
  ProfileUsernameRoute: typeof ProfileUsernameRoute
  RCodeRoute: typeof RCodeRoute
  SettingsProfileRoute: typeof SettingsProfileRoute
  SettingsSecurityRoute: typeof SettingsSecurityRoute
  ApiPublicHooksProcessMailingQueueRoute: typeof ApiPublicHooksProcessMailingQueueRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed': {
      id: '/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof FeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/become-creator': {
      id: '/become-creator'
      path: '/become-creator'
      fullPath: '/become-creator'
      preLoaderRoute: typeof BecomeCreatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/security': {
      id: '/settings/security'
      path: '/settings/security'
      fullPath: '/settings/security'
      preLoaderRoute: typeof SettingsSecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/profile': {
      id: '/settings/profile'
      path: '/settings/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof SettingsProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$code': {
      id: '/r/$code'
      path: '/r/$code'
      fullPath: '/r/$code'
      preLoaderRoute: typeof RCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$username': {
      id: '/profile/$username'
      path: '/profile/$username'
      fullPath: '/profile/$username'
      preLoaderRoute: typeof ProfileUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creator/wallet': {
      id: '/creator/wallet'
      path: '/creator/wallet'
      fullPath: '/creator/wallet'
      preLoaderRoute: typeof CreatorWalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creator/subscription-plans': {
      id: '/creator/subscription-plans'
      path: '/creator/subscription-plans'
      fullPath: '/creator/subscription-plans'
      preLoaderRoute: typeof CreatorSubscriptionPlansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creator/posts': {
      id: '/creator/posts'
      path: '/creator/posts'
      fullPath: '/creator/posts'
      preLoaderRoute: typeof CreatorPostsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creator/mailing': {
      id: '/creator/mailing'
      path: '/creator/mailing'
      fullPath: '/creator/mailing'
      preLoaderRoute: typeof CreatorMailingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creator/dmca': {
      id: '/creator/dmca'
      path: '/creator/dmca'
      fullPath: '/creator/dmca'
      preLoaderRoute: typeof CreatorDmcaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creator/coupons': {
      id: '/creator/coupons'
      path: '/creator/coupons'
      fullPath: '/creator/coupons'
      preLoaderRoute: typeof CreatorCouponsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creator/analytics': {
      id: '/creator/analytics'
      path: '/creator/analytics'
      fullPath: '/creator/analytics'
      preLoaderRoute: typeof CreatorAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creator/affiliate': {
      id: '/creator/affiliate'
      path: '/creator/affiliate'
      fullPath: '/creator/affiliate'
      preLoaderRoute: typeof CreatorAffiliateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$code': {
      id: '/c/$code'
      path: '/c/$code'
      fullPath: '/c/$code'
      preLoaderRoute: typeof CCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/moderation': {
      id: '/admin/moderation'
      path: '/admin/moderation'
      fullPath: '/admin/moderation'
      preLoaderRoute: typeof AdminModerationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/kyc': {
      id: '/admin/kyc'
      path: '/admin/kyc'
      fullPath: '/admin/kyc'
      preLoaderRoute: typeof AdminKycRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dmca': {
      id: '/admin/dmca'
      path: '/admin/dmca'
      fullPath: '/admin/dmca'
      preLoaderRoute: typeof AdminDmcaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/process-mailing-queue': {
      id: '/api/public/hooks/process-mailing-queue'
      path: '/api/public/hooks/process-mailing-queue'
      fullPath: '/api/public/hooks/process-mailing-queue'
      preLoaderRoute: typeof ApiPublicHooksProcessMailingQueueRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BecomeCreatorRoute: BecomeCreatorRoute,
  ChatRoute: ChatRoute,
  ExploreRoute: ExploreRoute,
  FeedRoute: FeedRoute,
  LoginRoute: LoginRoute,
  NotificationsRoute: NotificationsRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SearchRoute: SearchRoute,
  SignupRoute: SignupRoute,
  AdminDmcaRoute: AdminDmcaRoute,
  AdminKycRoute: AdminKycRoute,
  AdminModerationRoute: AdminModerationRoute,
  CCodeRoute: CCodeRoute,
  CreatorAffiliateRoute: CreatorAffiliateRoute,
  CreatorAnalyticsRoute: CreatorAnalyticsRoute,
  CreatorCouponsRoute: CreatorCouponsRoute,
  CreatorDmcaRoute: CreatorDmcaRoute,
  CreatorMailingRoute: CreatorMailingRoute,
  CreatorPostsRoute: CreatorPostsRoute,
  CreatorSubscriptionPlansRoute: CreatorSubscriptionPlansRoute,
  CreatorWalletRoute: CreatorWalletRoute,
  ProfileUsernameRoute: ProfileUsernameRoute,
  RCodeRoute: RCodeRoute,
  SettingsProfileRoute: SettingsProfileRoute,
  SettingsSecurityRoute: SettingsSecurityRoute,
  ApiPublicHooksProcessMailingQueueRoute:
    ApiPublicHooksProcessMailingQueueRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
